dist: trusty
language: go
services:
- docker
go:
- 1.12.x
env:
- GOMAXPROCS=4 GO111MODULE=on
install:
- go get golang.org/x/crypto/pkcs12
- go get github.com/pkg/errors
- go get github.com/hashicorp/terraform@v0.12.19
- go mod tidy
- go mod vendor
script:
- make dist
before_deploy:
- export TRAVIS_TAG="v3.0.4"
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: YeP33TYT4M9lINGBZscSBRUpAQWJNz/bQS0oaPdvUklF5noKccUsVUgMbtqy7VxIYes8UsVQTtiOExMRVq2j6Gcz7oiLpG5stmFERY7cZG4SKI9Q4lTMcZZZFn5IO0FP4+WF36ztuOGXXi8y40nlYqq/A2NS93C1soZ9Wb/nihmhGIoBOIBo9yfyt7n/qTiVneMeDs66nzc8K3GmzaP9vA2ydWprSrzIDdUYW474pCj7/JzXN1S/3ACZtA7Yt6BQujaacZOhjIjPh/GIYscN5R1t1q0VuFC4AFpxKk52syLNUuf7t25+1simPCS+BhL8BnqsPeXyuJc1ZwHfCmaZ8anqBX75Dsdy+3yQBqHDOfR8nRRrA3YZtViXzeAc+ki6zlHmbc717rxa8XyWecHwBkI/8c4xiKkOOf1DOfv+M/u1VvOz0Y+1stkg6VCwXVAqMAu3YIlHRdl0HyIZx9myXLo5qHLSsvCNzSwp5zdjm1+6KHmY5rTTSOdi9R1yHUGQK+aSrVb2bf5cX6ONCEPMgLnrHCaMSy/+TfX3/0JO69XGOEWiIMXcnRvjDjBIOaNNrnSwkXIGe0sq+96IcSCZj6E0SVbhLuWS6fKTkpn5mV1iKqkNPIGUD++a8BxC09DDnE0+9vbMFQGPuWoEaZ68DDs5oP2RGlYDzmlIGZLfsIw=
  file: _bin/terraform-provider-ddcloud.*.zip
  on:
    repo: DimensionDataResearch/dd-cloud-compute-terraform
    branch: terraform_v12_upgrade
    tags: true
  cleanup: 'false'
